application: tf2apiproxy
version: 7
runtime: python
api_version: 1


handlers:

- url: /api/v1/.*
  script: proxyapp.py

- url: /admin.d/.*
  script: adminapp.py
  login: admin

- url: /favicon.ico
  static_files: htdocs/favicon.ico
  upload: htdocs/favicon.ico

- url: /.*
  static_files: htdocs/index.html
  upload: htdocs/index.html
